default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: localhost
  ports: 3306 

development:
  <<: *default
  database: kioku_development

test:
  <<: *default
  database: kioku_test

production:
  <<: *default
  database: kioku_production
  adapter: mysql2
  encoding: utf8
  # username: <%= Rails.application.credentials.db[:user_name] %>
  # password: <%= ENV['PASSWORD2'] %>
  # host: <%= Rails.application.credentials.db[:endpoint] %>
  socket: /var/lib/mysql/mysql.sock