default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: kioku_development

test:
  <<: *default
  database: kioku_test

production:
  <<: *default
  database: kioku_production
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  host: <%= Rails.application.credentials.db[:endpoint] %>
  username: <%= Rails.application.credentials.db[:user_name] %>
  password: <%= Rails.application.credentials.db[:password] %>
  socket: <%= Rails.application.credentials.db[:socket] %>
  pool: 20
  timeout: 1000
